---
- hosts: icpcluster
  remote_user: root
  vars_files:
  - variables
  tasks:

  - name: Registrar RHEL
    redhat_subscription:
      state: present
      username: jlizano@gbm.net
      password: xxxxxxxxxxxxxxxxxxxxx
      auto_attach: true

  - name: Agregar repositorio epel
    shell: yum -y install http://download.fedoraproject.org/pub/epel/7Server/x86_64/Packages/e/epel-release-7-12.noarch.rpm

  - name: Instalar librerias necesarias para ICP
    yum:
      name:
        - nano
        - vim
        - screen
        - git
        - socat
        - net-tools
        - python-setuptools
        - wget
        - unzip
        - sshpass
        - curl
        - bind-utils
        - nfs-utils
        - yum-plugin-aliases
      state: present

  - name: Deshabilitar SELinux
    selinux:
      state: disabled

  - name: Limites core
    pam_limits:
      domain: '*'
      limit_type: "{{ item }}"
      limit_item: core
      value: '390001'
    with_items:
       - soft
       - hard

  - name: Limites nproc
    pam_limits:
      domain: '*'
      limit_type: "{{ item }}"
      limit_item: nproc
      value: '4097'
    with_items:
       - soft
       - hard

  - name: Limites nofile
    pam_limits:
      domain: '*'
      limit_type: "{{ item }}"
      limit_item: nofile
      value: '32770'
    with_items:
       - soft
       - hard

  - name: Limites fsize
    pam_limits:
      domain: '*'
      limit_type: "{{ item }}"
      limit_item: fsize
      value: unlimited
    with_items:
       - soft
       - hard

  - name: Detener servicio firewalld
    systemd:
      state: stopped
      name: firewalld

  - name: Deshabilitar servicio firewalld
    systemd:
      name: firewalld
      enabled: no
      masked: no

  - name: Instalar pip python
    easy_install:
      name: pip
      state: latest

  - name: Modificando linea de /etc/yum/pluginconf.d/search-disabled-repos.conf
    lineinfile:
      path: /etc/yum/pluginconf.d/search-disabled-repos.conf
      regexp: '^notify_only=1'
      insertafter: '^#notify_only=1'
      line: notify_only=0

  - name: Modificar sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin prohibit-password'
      insertafter: '^#PermitRootLogin prohibit-password'
      line: PermitRootLogin yes

  - name: Detener servicio sshd
    systemd:
      state: stopped
      name: sshd

  - name: Iniciar servicio sshd
    systemd:
      state: started
      name: sshd

  - name: Copiar archivo template de hosts al servidor
    template:
      src: hosts1.txt
      dest: /etc/hosts

  - name: Reiniciar las máquinas para hacer todos los cambios sean efectivos
    reboot:
      reboot_timeout: 120

  - name: Esperar 1 minuto mientras las máquinas inician
    wait_for_connection:
      delay: 30
      timeout: 60

  - name: Generate SSH keys
    shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
    args:
      creates: /root/.ssh/id_rsa

  - name: Generar ssh de acceso a los servers
    command: "{{ item }}"
    with_items:
       - sshpass -p {{master_node_pass}} ssh-copy-id root@{{master_node}} -o StrictHostKeyChecking=no

  - name: Copiar docker a todos los equipos
    copy:
      src: "{{path_icp}}/icp-docker-18.09.7_x86_64.bin"
      dest: /opt

  - name: Copiar ICP a master node
    copy:
      src: "{{path_icp}}/ibm-cloud-private-x86_64-3.2.1.tar.gz"
      dest: /opt
